astelle/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.shortcuts import render

urlpatterns = [
    url(r'^kronos/', include('kronos.urls', namespace="kronos")),
    url(r'^hq/', include('hq.urls', namespace="hq")),
    url(r'^admin/', include(admin.site.urls)),
]

hq/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.overview, name="overview"),
    path('project/add/', views.project_add, name="project_add"),
    path('project/<int:project_id>/', include([
        path('', views.project_detail, name="project_detail"),
        path('archive/', views.project_archive, name="project_archive"),
        path('delete/', views.project_delete, name="project_delete"),
        ])),
    path('address/add/', views.address_add, name="address_add"),
    path('address/<int:address_id>', include([
        path('', views.address_detail, name="address_detail"),
        path('delete/', views.address_delete, name="address_delete"),
        ])),
]

kronos/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.overview, name="overview"),
    path('add/', views.timecard_add, name="timecard_add"),
    path('complete/', views.timecard_complete_index, name="timecard_complete_index"),
    path('timecards/', views.timecard_index, name="timecard_index"),
    path('<int:timecard_id>/', include([
        path('', views.timecard_detail, name="timecard_detail"),
        path('complete/', views.timecard_complete, name="timecard_complete"),
        path('review/', views.timecard_review, name="timecard_review"),
        path('update/', views.timecard_update, name="timecard_update"),
        path('delete/', views.timecard_delete, name="timecard_delete"),
        path('task/add/', views.task_add, name="task_add"),
        path('task/<int:task_id>/', include([
            path('', views.task_detail, name="task_detail"),
            path('update/', views.task_update, name="task_update"),
            path('copy/', views.task_copy, name="task_copy"),
            path('delete/', views.task_delete, name="task_delete"),
        ])),
    ])),
]

workroom/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('kronos/', include(('kronos.urls', 'kronos'), namespace='kronos')),
    path('atom/', include(('atom.urls', 'atom'), namespace='atom')),
    path('hq/', include(('hq.urls', 'hq'), namespace='hq')),
    path('stronghold/', include(('stronghold.urls', 'stronghold'), namespace='stronghold')),
    path('admin/', admin.site.urls),
]

atom/models.py
from django.db import models

class LaborGroup(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=72)

    def __str__(self):
        return "%d - %s" % (self.number, self.name)

class LaborItem(models.Model):
    group = models.ForeignKey(LaborGroup, on_delete=models.CASCADE)
    number = models.IntegerField()
    description = models.CharField(max_length=72)

    def __str__(self):
        return "%d %s" % (self.number, self.description)    

class LaborClass(models.Model):
    number = models.CharField(max_length=8)
    name = models.CharField(max_length=72)
    description = models.TextField(max_length=72)
    company_rate = models.DecimalField(max_digits=8, decimal_places=2)
    employee_rate = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return "%s %s" % (self.number, self.name)

    class Meta:
        verbose_name_plural = "labor classes"

kronos/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from atom.models import LaborItem, LaborClass


class PayPeriod(models.Model):
    start = models.DateField()
    end = models.DateField()

    def __str__(self):
        return "%s through %s." % (self.start,
            self.end)


class Timecard(models.Model):
    employee = models.ForeignKey(User, on_delete=models.CASCADE)
    pay_period = models.ForeignKey(PayPeriod, on_delete=models.CASCADE)
    submission_notes = models.TextField(blank=True)
    complete = models.BooleanField(default=False)
    reviewed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def get_total_tasks_duration(self):
        """Return the total time duration of all tasks in hours as a float."""
        total = 0
        for task in Task.objects.filter(timecard__pk=self.id):
            total += task.get_task_duration()
        return total
        del total

    @property
    def is_past_due(self):
        if datetime.date.today() > self.pay_period.end:
            return True
        return False

    def __str__(self):
        return "%s, %s through %s." % (self.employee.first_name, self.pay_period.start,
            self.pay_period.end)

    class Meta:
        permissions = (
            ('can_review_timecards', "Can review timecards"),
            )

class Task(models.Model):
    timecard = models.ForeignKey(Timecard, on_delete=models.CASCADE)
    employee = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey('hq.Project', on_delete=models.CASCADE)
    description = models.TextField()
    started = models.DateTimeField()
    finished = models.DateTimeField()
    labor_item_number = models.ForeignKey(LaborItem, on_delete=models.CASCADE)
    li_class = models.ForeignKey(LaborClass, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def get_task_duration(self):
        """Return the task duration in hours as a float"""
        duration = round((self.finished - self.started).seconds / 3600, 2)
        if duration > 8:
            return duration - 0.5
        return duration

    def __str__(self):
        return "%s, %s (%s)" % (self.employee.first_name, self.description, self.started)

kronos/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import PayPeriod, Timecard, Task
from django.contrib.auth.models import User
from hq import models as hq_models
from atom.models import LaborGroup, LaborItem, LaborClass
from django.db.models import Sum
import datetime


@login_required(login_url="/login/")
def overview(request):
    """/kronos/
    Return overview render.
    """
    timecards = Timecard.objects.all().filter(employee=request.user, complete=False)
    return render(request, 'kronos/overview.html', {
        'timecards': timecards
        })

@login_required(login_url="/login/")
def timecard_add(request):
    """/kronos/timecard/add/
    If POST, process data and create timecard.
    """
    if request.method == "POST":
        p = request.POST["pay_period"]
        pay_period = PayPeriod.objects.get(pk=p)
        timecard = Timecard.objects.create(
            employee=request.user,
            pay_period=pay_period
            )
        timecard.save()

        return HttpResponseRedirect('/kronos/%s' % (timecard.id))

    else:
        pay_periods = PayPeriod.objects.order_by('-start')[:3]
        return render(request, 'kronos/timecard_add.html', {'pay_periods': pay_periods})

@login_required(login_url="/login/")
def timecard_detail(request, timecard_id):
    """/kronos/1/
    Return timecard detail render.
    """
    timecard = Timecard.objects.get(pk=timecard_id)
    tasks = Task.objects.all().filter(timecard=timecard).order_by('started')

    return render(request, 'kronos/timecard_detail.html', {
        'timecard': timecard,
        'tasks': tasks
        })

@login_required(login_url="/login/")
def timecard_complete(request, timecard_id):
    """/kronos/1/complete/
    Have to be a manager.
    If POST process data.
    """
    if request.method == "POST":
        timecard = Timecard.objects.get(pk=timecard_id)
        timecard.submission_notes = request.POST["submission_notes"]
        timecard.complete = True
        timecard.save()

        return HttpResponseRedirect('/kronos/')
    else:
        try:
            timecard = Timecard.objects.get(pk=timecard_id)
            tasks = Task.objects.all().filter(timecard=timecard).order_by('started')
        except Timecard.DoesNotExist:
            raise Http404("Timecard does not exist.")
        return render(request, 'kronos/timecard_review.html', {
            'timecard': timecard,
            'tasks': tasks
            })

@permission_required('kronos.can_review_timecards')
@login_required(login_url="/login/")
def timecard_review(request, timecard_id):
    """/kronos/1/review/
    Have to be a manager.
    If POST, timecard_id, mark timecard as reviewed.
    """
    if request.method == "POST":
        timecard = Timecard.objects.get(pk=timecard_id)
        timecard.reviewed = True
        timecard.save()

        return HttpResponseRedirect('/kronos/timecards/')
    else:
        try:
            timecard = Timecard.objects.get(pk=timecard_id)
            tasks = Task.objects.all().filter(timecard=timecard).order_by('started')
        except Timecard.DoesNotExist:
            raise Http404("Timecard does not exist.")
        return render(request, 'kronos/timecard_review.html', {
            'timecard': timecard,
            'tasks': tasks
            })

@login_required(login_url="/login/")
def timecard_complete_index(request):
    """/kronos/complete/
    Return a list of completed timecards.
    """
    try:
        timecard = Timecard.objects.order_by('-pay_period').filter(complete=True, employee=request.user)
    except Timecard.DoesNotExist:
        raise Http404("No timecards does not exist.")
    return render(request, 'kronos/timecard_complete.html', {'timecards': timecard})

@permission_required('kronos.can_review_timecards')
@login_required(login_url="/login/")
def timecard_index(request):
    """/kronos/timecards/
    Return a list of all timecards.
    """
    try:
        pay_period= PayPeriod.objects.order_by('-start')
    except PayPeriod.DoesNotExist:
        raise Http404("Timecards do not exist.")
    return render(request, 'kronos/timecard_index.html', {'pay_periods': pay_period})

@login_required(login_url="/login/")
def timecard_update(request, timecard_id):
    pass

@login_required(login_url="/login/")
def task_add(request, timecard_id):
    """/kronos/task/add/
    If POST process data and add task to timecard.
    """
    if request.method == "POST":
        employee = request.POST["employee"]
        date = request.POST["date"]
        project_id = request.POST["project"]
        description = request.POST["description"]
        start_time = request.POST["start_time"]
        end_time = request.POST["end_time"]
        labor_item_id = request.POST["labor_item_number"]
        li_class_id = request.POST["li_class"]

        started = "%s %s" % (date, start_time)
        finished = "%s %s" % (date, end_time)

        project = hq_models.Project.objects.get(id=project_id)
        user = User.objects.get(id=employee)
        timecard = Timecard.objects.get(id=timecard_id)
        labor_item = LaborItem.objects.get(id=labor_item_id)
        li_class = LaborClass(id=li_class_id)

        t = Task.objects.create(
            employee=user,
            timecard=timecard,
            project = project,
            description = description,
            started = started,
            finished = finished,
            labor_item_number = labor_item,
            li_class = li_class
            )
        t.save()

        return HttpResponseRedirect('/kronos/%s' % (timecard_id))

    else:
        li_classes = LaborClass.objects.all()
        labor_groups = LaborGroup.objects.all()
        projects = hq_models.Project.objects.all().filter(archived=False)
        return render(request, 'kronos/task_add.html', {
            'projects': projects,
            'timecard_id': timecard_id,
            'labor_groups': labor_groups,
            'li_classes': li_classes
            })

@login_required(login_url="/login/")
def timecard_delete(request, timecard_id):
    """/kronos/1/delete/
    Deletes the timecard with id.
    """
    t = Timecard.objects.get(pk=timecard_id)
    t.delete()
    return HttpResponseRedirect('/kronos/')    

@login_required(login_url="/login/")
def task_detail(request, timecard_id, task_id):
    try:
        timecard = Timecard.objects.get(pk=timecard_id)
        task = Task.objects.get(pk=task_id)
    except Timecard.DoesNotExist:
        raise Http404("Task or Timecard do not exist.")
    return render(request, 'kronos/task_detail.html', {
        'timecard': timecard,
        'task': task
        })


@login_required(login_url="/login/")
def task_update(request, timecard_id, task_id):
    """/kronos/1/task/1/update/
    Updates task with id.
    """
    if request.method == "POST":

        date = request.POST["date"]
        project_id = request.POST["project"]
        description = request.POST["description"]
        start_time = request.POST["start_time"]
        end_time = request.POST["end_time"]
        labor_item_id = request.POST["labor_item_number"]
        li_class_id = request.POST["li_class"]

        started = "%s %s" % (date, start_time)
        finished = "%s %s" % (date, end_time)

        project = hq_models.Project.objects.get(pk=project_id)
        labor_item = LaborItem.objects.get(pk=labor_item_id)
        li_class = LaborClass(pk=li_class_id)

        task = Task.objects.get(pk=task_id)
        
        task.project = project
        task.description = description
        task.started = started
        task.finished = finished
        task.labor_item_number = labor_item
        task.li_class = li_class
        
        task.save()

        return HttpResponseRedirect('/kronos/%s/task/%s' % (timecard_id, task_id))
    else:
        timecard = Timecard.objects.get(pk=timecard_id)
        task = Task.objects.get(pk=task_id)
        li_classes = LaborClass.objects.all()
        labor_groups = LaborGroup.objects.all()
        projects = hq_models.Project.objects.all().filter(archived=False)
        return render(request, 'kronos/task_update.html', {
            'timecard': timecard,
            'task': task,
            'projects': projects,
            'labor_groups': labor_groups,
            'li_classes': li_classes
            })

@login_required(login_url="/login/")
def task_copy(request, timecard_id, task_id):
    """/kronos/1/task/1/delete/
    Copy task with id, replace times with today
    """
    t = Task.objects.get(pk=task_id)
    t.pk = None

    today = datetime.datetime.now()
    
    t.started = t.started.replace(year=today.year, month=today.month, day=today.day)
    t.finished = t.finished.replace(year=today.year, month=today.month, day=today.day)
    t.save()
    return HttpResponseRedirect('/kronos/%s/' % (timecard_id))


@login_required(login_url="/login/")
def task_delete(request, timecard_id, task_id):
    """/kronos/1/task/1/delete/
    Delete the task with id.
    """
    t = Task.objects.get(pk=task_id)
    t.delete()
    return HttpResponseRedirect('/kronos/%s' % (timecard_id))

kronos/templates/kronos/complete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Wallyworks</h1>

    <section>
        <h3>Your completed timecards</h3>
        {% if timecards %}
            <ul>
            {% for tc in timecards %}
                <li>
                    <a href="{% url 'kronos:detail' tc.id %}">{{ tc.pay_period_start }} through {{ tc.pay_period_end }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p><em>You have no completed timecards</em></p>
        {% endif %}
    </section>
{% endblock %}

kronos/templates/kronos/overview.html
{% extends 'base.html' %}

{% block content %}
    <section class="detail">
        {% if perms.kronos.can_review_timecards %}
        <div class="menu">
            <a class="" href="{% url 'kronos:timecard_index' %}">Review Timecards</a>
        </div>
        {% endif %}
        <h1>Timecards</h1>
        <a class="action-button" href="{% url 'kronos:timecard_add' %}">Start a new Timecard</a>
        {% if timecards %}
            {% for timecard in timecards %}
                <p>
                    <a href="{% url 'kronos:timecard_detail' timecard.id %}"><strong>{{ timecard.pay_period.start|date:"M d" }} - {{ timecard.pay_period.end|date:"d, Y" }}</strong></a><br>
                    <small>
                        {% if timecard.is_past_due %}
                            <span class="past-due">Past due!</span>
                        {% endif %}
                        {% if timecard.task_set.count == 1 %}
                            {{ timecard.task_set.count }} task,
                        {% else %}
                            {{ timecard.task_set.count }} tasks,
                        {% endif %}
                        {{ timecard.get_total_tasks_duration }} hrs
                    </small>
                </p>
            {% endfor %}
        {% else %}
            <p><em>You have no current timecard</em></p>
        {% endif %}
    </section>
    <section>
        <p>
            <a class="completed-timecards" href="{% url 'kronos:timecard_complete_index' %}">Completed timecards…</a>
        </p>
    </section>
{% endblock %}

kronos/templates/kronos/task_add.html
{% extends 'base.html' %}

{% block stylesheets %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/datepickr.css' %}"/>
{% endblock %}

{% block content %}
    <div class="backlink">
        <span>←</span>
        <a href="{% url 'kronos:timecard_detail' timecard_id %}">Back to timecard</a>
    </div>
<form method="post" action="{% url 'kronos:task_add' timecard_id %}">
    {% csrf_token %}
    <input type="hidden" name="employee" value="{{ user.id }}">

    <section class="detail">
        <p>
            <label for="date">Date:</label>
            <br>
            <input name="date" class="datepickr" readonly="true" placeholder="2000-01-01" required>
        </p>
        <p>
            <label for="project">Project:</label>
            <br>
            <select name="project" required>
                <option value="" selected="selected">-------</option>
                {% if projects %}
                    {% for p in projects %}
                        <option value="{{ p.id }}">{{ p.name }}</option>
                    {% endfor %}
                {% endif %}
            </select>
            <br>
            <small>
                Don't see the project you're looking for?
                <a href="{% url 'hq:project_add' %}">+ Add a new project</a>
            </small>
        </p>

        <p>
            <label for="start_time">Start:</label>
            <input name="start_time" type="time" placeholder="8:00" required>
        </p>
        <p>    
            <label for="end_time">End:</label>
            <input name="end_time" type="time" placeholder="12:00" required>
        </p>

        <p>
            <label for="description">Task description:</label>
            <br>
            <textarea name="description" placeholder="What did you work on?"  required></textarea>
        </p>
        <p>
            <label for="labor_item_number">Labor item number:</label>
            <br>
            {% if labor_groups %}
                <select name="labor_item_number" required>
                    <option value="" selected="selected">-------</option>
                {% for group in labor_groups %}
                    <optgroup label="{{ group.name }}">
                    {% for item in group.laboritem_set.all %}
                        <option value="{{ item.id }}">{{ item.number }}: {{ item.description }}</option>
                    {% endfor %}
                    </optgroup>
                {% endfor %}
                </select>
            {% else %}
                <p>There are no Labor items yet.</p>
            {% endif %}
        </p>
        <p>
            <label for="li_class">L&amp;I class:</label>
            <br>
            {% if li_classes %}
                <select name="li_class" required>
                    <option value="" selected="selected">-------</option>
                {% for class in li_classes %}
                    <option value="{{ class.id }}">{{ class.number }}: {{ class.name }}</option>
                {% endfor %}
                </select>
            {% else %}
                <p>There are no Labor Classes yet.</p>
            {% endif %}
        </p>
    </section>
    <input type="submit" value="Add this task">
</form>
{% endblock %}

{% block javascripts %}
    <script src="{% static 'js/datepickr.js' %}"></script>
    <script>
        // Custom date format
        datepickr('.datepickr', { dateFormat: 'Y-m-d' });
    </script>
{% endblock %}

kronos/templates/kronos/task_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="backlink">
        <span>←</span>
        <a href="{% url 'kronos:timecard_detail' timecard.id %}">Back to timecard</a>
    </div>
    <section class="timecard-detail">
        <div class="menu">
            <a href="{% url 'kronos:task_update' timecard.id task.id %}">Edit/delete this…</a>
            <a href="{% url 'kronos:task_copy' timecard.id task.id %}">Duplicate this…</a>
        </div>

        <h1>Task Details</h1>
        <table>
            <tbody>
                <tr>
                    <th>Date:</th>
                    <td>{{ task.started|date:"M d" }}</td>
                </tr>
                <tr>
                    <th>Project:</th>
                    <td>{{ task.project.name }}</td>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td>{{ task.description }}</td>
                </tr>
                <tr>
                    <th>LI number:</th>
                    <td>{{ task.labor_item_number.number }} <em>{{ task.labor_item_number.description }}</em></td>
                </tr>
                <tr>
                    <th>L&I class:</th>
                    <td>{{ task.li_class.number }} <em>{{ task.li_class.name }}</em></td>
                </tr>
                <tr>
                    <th>Start:</th>
                    <td>{{ task.started|date:"g:i A" }}</td>
                </tr>
                <tr>
                    <th>End:</th>
                    <td>{{ task.finished|date:"g:i A" }}</td>
                </tr>
                <tr>
                    <th>Total time:</th>
                    <td>{{ task.get_task_duration }} hrs.</td>
                </tr>
                <tr>

                </tr>
            </tbody>
        </table>
    </section>
{% endblock %}

kronos/templates/kronos/task_update.html
{% extends 'base.html' %}

{% block stylesheets %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/datepickr.css' %}"/>
{% endblock %}

{% block content %}
    <div class="backlink">
        <span>←</span>
        <a onclick="goBack()" href="">Back to task</a>
    </div>
<form method="post" action="{% url 'kronos:task_update' timecard.id task.id %}">
    {% csrf_token %}

    <section class="detail">
        <div class="menu">
            <a class="delete" href="{% url 'kronos:task_delete' timecard.id task.id %}" onclick="if (!confirm('Are you sure you want to delete this?')) return false;">Delete this</a>
        </div>

        <p>
            <label for="date">Date:</label>
            <br>
            <input name="date" class="datepickr" readonly="true" placeholder="2000-01-01" value="{{ task.started|date:'Y-m-d' }}" required>
        </p>
        <p>
            <label for="project">Project:</label>
            <br>
            <select name="project" required>
                {% if projects %}
                    {% for project in projects %}
                        {% if project.id == task.project.id %}
                            <option value="{{ project.id }}" selected="selected">*{{ project.name }}</option>
                        {% else %}
                            <option value="{{ project.id }}">{{ project.name }}</option>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </select>
            <br>
            <small>
                Don't see the project you're looking for?
                <a href="{% url 'hq:project_add' %}">+ Add a new project</a>
            </small>
        </p>

        <p>
            <label for="start_time">Start:</label>
            <input name="start_time" type="time" placeholder="8:00" value="{{ task.started|date:'H:i' }}" required>
        </p>
        <p>    
            <label for="end_time">End:</label>
            <input name="end_time" type="time" placeholder="12:00" value="{{ task.finished|date:'H:i' }}" required>
        </p>

        <p>
            <label for="description">Task description:</label>
            <br>
            <textarea name="description" placeholder="What did you work on?"  required>{{ task.description }}</textarea>
        </p>
        <p>
            <label for="labor_item_number">Labor item number:</label>
            <br>
            {% if labor_groups %}
                <select name="labor_item_number" required>
                {% for group in labor_groups %}
                    <optgroup label="{{ group.name }}">
                    {% for item in group.laboritem_set.all %}
                        {% if item.id == task.labor_item_number.id %}
                            <option value="{{ item.id }}" selected="selected">*{{ item.number }}: {{ item.description }}</option>
                        {% else %}
                            <option value="{{ item.id }}">{{ item.number }}: {{ item.description }}</option>
                        {% endif %}
                    {% endfor %}
                    </optgroup>
                {% endfor %}
                </select>
            {% endif %}
        </p>
        <p>
            <label for="li_class">L&amp;I class:</label>
            <br>
            {% if li_classes %}
                <select name="li_class" required>
                {% for class in li_classes %}
                    {% if class.id == task.li_class.id %}
                        <option value="{{ class.id }}" selected="selected">*{{ class.number }}: {{ class.name }}</option>
                    {% else %}
                        <option value="{{ class.id }}">{{ class.number }}: {{ class.name }}</option>
                    {% endif %}
                {% endfor %}
                </select>
            {% endif %}
        </p>
    </section>
    <input type="submit" value="Save changes">
</form>
{% endblock %}

{% block javascripts %}
    <script src="{% static 'js/datepickr.js' %}"></script>
    <script>
        // Custom date format
        datepickr('.datepickr', { dateFormat: 'Y-m-d' });
    </script>
{% endblock %}

kronos/templates/kronos/timecard_detail.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="backlink">
        <span>←</span>
        <a href="{% url 'kronos:overview' %}">Back to timecards</a>
    </div>

    <section class="timecard-detail">
        {% if timecard.is_past_due and not timecard.complete %}
                <span class="past-due">Past due!</span>
        {% endif %}
        <h1>{{ timecard.employee.first_name }} {{ timecard.employee.last_name }}'s Timecard</h1>
        <h2>{{ timecard.pay_period.start|date:"M d" }} - {{ timecard.pay_period.end|date:"d, Y" }}</h2>
        {% if not timecard.complete %}
        <section>
            <a class="action-button" href="{% url 'kronos:task_add' timecard.id %}">Add another Task</a>
        </section>
        {% endif %}
        {% if timecard.submission_notes %}
            <blockquote cite="{{ timecard.employee.first_name }} {{ timecard.employee.last_name }}">{{ timecard.submission_notes }}<br>
                —{{ timecard.employee.first_name }} {{ timecard.employee.last_name }}
            </blockquote>
        {% endif %}
        {% if tasks %}
            <table class="tasks">
                <thead>
                    <tr class="task">
                        <th>Date</th>
                        <th>Project</th>
                        <th>LI number</th>
                        <th>Description</th>
                        <th>Start time</th>
                        <th>End time</th>
                        <th>L&I class</th>
                        <th>Task Time</th>
                    </tr>
                </thead>
                <tbody>
                {% for task in tasks %}
                    <tr class="task">
                        <td>{{ task.started|date:"M d" }}</td>
                        <td>{{ task.project }}</td>
                        <td>{{ task.labor_item_number.number }}</td>
                        <td>
                            <a href="{% url 'kronos:task_detail' timecard.id task.id %}">{{ task.description }}</a>
                        </td>
                        <td>{{ task.started|date:"g:i A" }}</td>
                        <td>{{ task.finished|date:"g:i A" }}</td>
                        <td>{{ task.li_class.number }}</td>
                        <td>{{ task.get_task_duration }} hrs.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <p class="total-hours"><strong>Total hours: {{ timecard.get_total_tasks_duration }}</strong></p>
        {% endif %}
    </section>
    {% if not timecard.complete %}
    <section>
        <p>Ready to submit your timecard? Leave an optional note and hit the botton below.</p>
        <form method="post" action="{% url 'kronos:timecard_complete' timecard.id %}">
            {% csrf_token %}
            <p>
                <label for="submission_notes">Submission notes:</label>
                <br>
                <textarea name="submission_notes" placeholder="Anything you'd like to tell the manager about your timecard?">{{ timecard.submission_notes }}</textarea>
            </p>
            <input type="submit" value="Submit for review" onclick="if (!confirm('Are you sure you want to submit this?')) return false;">
        </form>
    </section>
    {% endif %}
{% endblock %}

kronos/templates/kronos/timecard_index.html
{% extends 'base.html' %}

{% block content %}

    {% if pay_periods %}
        <section class="detail">
            <h1>All timecards</h1>
            {% for pp in pay_periods %}
                <br>
                <p><strong>{{ pp.start|date:"M d" }} - {{ pp.end|date:"d, Y" }}</strong></p>
                {% for timecard in pp.timecard_set.all %}
                <p>
                    <a href="{% url 'kronos:timecard_review' timecard.id %}"><strong>{{ timecard.employee.first_name }} {{ timecard.employee.last_name }}</strong></a>
                    <small>
                        {% if not timecard.reviewed %}
                            <span class="not-reviewed">&#10007; not reviewed</span>
                        {% endif %}
                    </small><br>
                    <small>
                        {% if timecard.task_set.count == 1 %}
                            {{ timecard.task_set.count }} task,
                        {% else %}
                            {{ timecard.task_set.count }} tasks,
                        {% endif %}
                        {{ timecard.get_total_tasks_duration }} hrs
                    </small>
                </p>
                {% endfor %}
            {% endfor %}
        </section>
    {% else %}
        <p><em>No timecards</em></p>
    {% endif %}
{% endblock %}