astelle/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.shortcuts import render

urlpatterns = [
    url(r'^kronos/', include('kronos.urls', namespace="kronos")),
    url(r'^hq/', include('hq.urls', namespace="hq")),
    url(r'^admin/', include(admin.site.urls)),
]

hq/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.overview, name="overview"),
    path('project/add/', views.project_add, name="project_add"),
    path('project/<int:project_id>/', include([
        path('', views.project_detail, name="project_detail"),
        path('archive/', views.project_archive, name="project_archive"),
        path('delete/', views.project_delete, name="project_delete"),
        ])),
    path('address/add/', views.address_add, name="address_add"),
    path('address/<int:address_id>', include([
        path('', views.address_detail, name="address_detail"),
        path('delete/', views.address_delete, name="address_delete"),
        ])),
]

timekeeper/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
]

workroom/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('kronos/', include(('kronos.urls', 'kronos'), namespace='kronos')),
    path('atom/', include(('atom.urls', 'atom'), namespace='atom')),
    path('hq/', include(('hq.urls', 'hq'), namespace='hq')),
    path('stronghold/', include(('stronghold.urls', 'stronghold'), namespace='stronghold')),
    path('admin/', admin.site.urls),
]

hq/models.py
from django.db import models

class Address(models.Model):
    street = models.CharField(max_length=72)
    city = models.CharField(max_length=72)
    state = models.CharField(max_length=2)
    zip_code = models.IntegerField(blank=True,null=True)

    def __str__(self):
        return "%s, %s, %s" % (self.street, self.city, self.state)

    class Meta:
        verbose_name_plural = "addresses"

class Project(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=128)
    address = models.ManyToManyField(Address)
    archived = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

hq/forms.py
from django import forms
from .models import Address, Project

class AddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = ('__all__')
        widgets = {
            'street': forms.TextInput(attrs= {
                'placeholder': '1037 Lawrence St'
                }),
            'city': forms.TextInput(attrs= {
                'placeholder': 'Port Townsend'
                }),
            'state': forms.TextInput(attrs= {
                'placeholder': 'WA'
                }),
            }

class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ('name', 'description', 'address')
        widgets = {
            'name': forms.TextInput(attrs = {
                'placeholder':'Doe: Home'
                }),
            'description': forms.TextInput(attrs = {
                'placeholder':'Build a new home for John Doe.'
                }),
            }
        labels = {
            'name': "Name your Project",
            }
        help_texts = {
            'address': "Ctrl-click to select multiple."
            }

hq/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import Address, Project
from .forms import AddressForm, ProjectForm

@login_required(login_url="/login/")
def overview(request):
    p = Project.objects.all().filter(archived=False)
    a = Address.objects.all()
    return render(request, 'hq/overview.html', {
        'projects': p,
        'addresses': a
        })

@login_required(login_url="/login/")
def project_add(request):
    """/hq/project/add/
    If POST process data and create project.
    """
    if request.method == "POST":

        f = ProjectForm(request.POST)

        new_project = f.save()

        new_project.save()

        return HttpResponseRedirect('/hq/project/%s' % (new_project.id))

    else:
        form = ProjectForm()
        return render(request, 'hq/project_add.html', {'form': form.as_p()})

@login_required(login_url="/login/")
def address_add(request):
    """/hq/address/add/
    If POST process data and create address.
    """
    if request.method == "POST":


        f = AddressForm(request.POST)

        new_address = f.save()

        new_address.save()

        return HttpResponseRedirect('/hq/address/%s' % (new_address.id))

    else:
        form = AddressForm()
        return render(request, 'hq/address_add.html', {'form': form.as_p()})

@login_required(login_url="/login/")
def project_detail(request, project_id):
    try:
        project = Project.objects.get(pk=project_id)
    except Project.DoesNotExist:
        raise Http404("Project does not exist.")
    return render(request, 'hq/project_detail.html', {
        'project': project
        })

@login_required(login_url="/login/")
def address_detail(request, address_id):
    try:
        address = Address.objects.get(pk=address_id)
    except Address.DoesNotExist:
        raise Http404("Address does not exist.")
    return render(request, 'hq/address_detail.html', {
        'address': address
        })

@login_required(login_url="/login/")
def project_delete(request, project_id):
    """/hq/1/project/1/delete/
    Delete the project with id.
    """
    p = Project.objects.get(pk=project_id)
    p.delete()
    return HttpResponseRedirect('/hq/')

@login_required(login_url="/login/")
def project_archive(request, project_id):
    p = Project.objects.get(pk=project_id)
    p.archived = True
    p.save()
    return HttpResponseRedirect('/hq/')

@login_required(login_url="/login/")
def address_delete(request, address_id):
    """/hq/1/address/1/delete/
    Delete the address with id.
    """
    a = Address.objects.get(pk=address_id)
    a.delete()
    return HttpResponseRedirect('/hq/')

hq/templates/hq/address_add.html
{% extends 'base.html' %}

{% block content %}
    <div class="backlink">
        <span>←</span>
        <a href="{% url 'hq:overview' %}">Back to addresses</a>
    </div>

    <section>
        <form method="post" action="{% url 'hq:address_add' %}">
            {% csrf_token %}
            <section class="detail">
            {{ form }}
            </section>
            <input type="submit" value="Add this Address">
        </form>
    </section>
{% endblock %}

hq/templates/hq/address_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="backlink">
        <span>←</span>
        <a href="{% url 'hq:overview' %}">Back to projects</a>
    </div>
    <section class="timecard-detail">
        <div class="menu">
            <a class="delete" href="{% url 'hq:address_delete' address.id %}" onclick="if (!confirm('Are you sure you want to delete this?')) return false;">Delete this</a>
        </div>
        <h1>Address</h1>
        <address>
            {{ address.street }}<br>
            {{ address.city }}<br>
            {{ address.state }}<br>
            {{ address.zip_code }}<br>
        </address>
    </section>
{% endblock %}

hq/templates/hq/overview.html
{% extends 'base.html' %}

{% block content %}
<section class="detail">
    <h1>Projects</h1>
    <a class="action-button" href="{% url 'hq:project_add' %}">Make a new Project</a>
    {% if projects %}
        {% for project in projects %}
            <p>
                <a href="{% url 'hq:project_detail' project.id %}"><strong>{{ project }}</strong></a>
                <br>
                {{ project.description }}
            </p>
        {% endfor %}
    {% else %}
        <p>There are no projects yet.</p>
    {% endif %}
</section>
<section class="detail">
    <h1>Addresses</h1>
    <a class="action-button small" href="{% url 'hq:address_add' %}">Add a new Address</a>
    {% if addresses %}
        <ul>
        {% for a in addresses %}
            <li><a href="{% url 'hq:address_detail' a.id %}">{{ a }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no addresses yet.</p>
    {% endif %}
</section>
{% endblock %}

hq/templates/hq/project_add.html
{% extends 'base.html' %}

{% block content %}
    <div class="backlink">
        <span>←</span>
        <a href="{% url 'hq:overview' %}">Back to projects</a>
    </div>

    <section>
        <form method="post" action="{% url 'hq:project_add' %}">
            <section class="detail">
                {% csrf_token %}
                <p>
                    {{ form }}
                </p>
                <p>
                    <small>Don't see the address you want? <a href="{% url 'hq:address_add' %}">+ Add a new address</a></small>
                </p>
            </section>
            <input type="submit" value="Make this Project">
        </form>
    </section>
{% endblock %}

hq/templates/hq/project_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="backlink">
        <span>←</span>
        <a href="{% url 'hq:overview' %}">Back to projects</a>
    </div>
    <section class="timecard-detail">
        <div class="menu">
            <a href="{% url 'hq:project_archive' project.id %}" onclick="if (!confirm('Are you sure you want to archive this?')) return false;">Archive this</a>
            <a class="delete" href="{% url 'hq:project_delete' project.id %}" onclick="if (!confirm('Are you sure you want to delete this?')) return false;">Delete this</a>
        </div>
        {% if project.archived %}<span class="archived"><em>This project is archived</em></span>{% endif %}
        <h1>
            {{ project.name }}
        </h1>
        <h2>{{ project.description }}</h2>
        {% if project.address %}
            {% for address in project.address_set.all %}
                <address>
                    {{ address.street }}<br>
                    {{ address.city }}<br>
                    {{ address.state }}<br>
                    {{ address.zip_code }}<br>
                </address>
            {% endfor %}
        {% endif %}
    </section>
{% endblock %}