astelle/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.shortcuts import render

urlpatterns = [
    url(r'^kronos/', include('kronos.urls', namespace="kronos")),
    url(r'^hq/', include('hq.urls', namespace="hq")),
    url(r'^admin/', include(admin.site.urls)),
]

hq/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.overview, name="overview"),
    path('project/add/', views.project_add, name="project_add"),
    path('project/<int:project_id>/', include([
        path('', views.project_detail, name="project_detail"),
        path('archive/', views.project_archive, name="project_archive"),
        path('delete/', views.project_delete, name="project_delete"),
        ])),
    path('address/add/', views.address_add, name="address_add"),
    path('address/<int:address_id>', include([
        path('', views.address_detail, name="address_detail"),
        path('delete/', views.address_delete, name="address_delete"),
        ])),
]

stronghold/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.overview, name="overview"),
    path('door/add/', views.door_add, name="door_add"),
    path('code/add/', views.code_add, name="code_add"),
    path('code/<int:code_id>/', include([
        path('', views.code_detail, name="code_detail"),
        path('delete/', views.code_delete, name="code_delete"),
        ])),
]

workroom/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('kronos/', include(('kronos.urls', 'kronos'), namespace='kronos')),
    path('atom/', include(('atom.urls', 'atom'), namespace='atom')),
    path('hq/', include(('hq.urls', 'hq'), namespace='hq')),
    path('stronghold/', include(('stronghold.urls', 'stronghold'), namespace='stronghold')),
    path('admin/', admin.site.urls),
]

stronghold/models.py
from django.db import models

class Door(models.Model):
    location = models.CharField(max_length=128)
    address = models.ForeignKey('hq.Address', on_delete=models.CASCADE)

    def __str__(self):
        return "%s (%s)" % (self.location, self.address)

class Code(models.Model):
    door = models.ManyToManyField(Door)
    number = models.IntegerField()
    permanent = models.BooleanField(default=False)
    belongs_to = models.CharField(max_length=128, blank=True)

    def __str__(self):
        return "%d" % (self.number)

    class Meta:
        permissions = (
            ('can_view_stronghold', "Can view Stronghold"),
            )

stronghold/forms.py
from django import forms
from .models import Door, Code

class DoorForm(forms.ModelForm):

    class Meta:
        model = Door
        fields = ('address', 'location')
        widgets = {
            'location': forms.TextInput(attrs = {
                'placeholder':'Front, back, etc.'
                }),
            }

class CodeForm(forms.ModelForm):

    class Meta:
        model = Code
        fields = ('number', 'permanent', 'belongs_to', 'door')
        widgets = {
            'belongs_to': forms.TextInput(attrs = {
                'placeholder':'John Doe'
                }),
            }
        labels = {
            'permanent': "This is a permanent code"
            }
        help_texts = {
            'door': "Ctrl-click to select multiple."
            }

stronghold/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import Door, Code
from .forms import DoorForm, CodeForm

@permission_required('stronghold.can_view_stronghold')
@login_required(login_url="/login/")
def overview(request):
    all_codes = Code.objects.all()
    perm_codes = all_codes.filter(permanent=True)
    tmp_codes = all_codes.filter(permanent=False)

    return render(request, 'stronghold/overview.html', {
        'perm_codes': perm_codes,
        'tmp_codes': tmp_codes
        })

@permission_required('stronghold.can_view_stronghold')
@login_required(login_url="/login/")
def door_index(request):
    pass

@permission_required('stronghold.can_view_stronghold')
@login_required(login_url="/login/")
def code_index(request):
    pass

@permission_required('stronghold.can_view_stronghold')
@login_required(login_url="/login/")
def door_add(request):
    if request.method == "POST":
        f = DoorForm(request.POST)
        new_door = f.save()
        new_door.save()

        return HttpResponseRedirect('/stronghold/')
    else:
        f = DoorForm()
        return render(request, 'stronghold/door_add.html', {'form': f.as_p()})

@permission_required('stronghold.can_view_stronghold')
@login_required(login_url="/login/")
def code_add(request):
    if request.method == "POST":
        f = CodeForm(request.POST)
        new_code = f.save()
        new_code.save()

        return HttpResponseRedirect('/stronghold/')
    else:
        f = CodeForm()
        return render(request, 'stronghold/code_add.html', {'form': f.as_p()})

@permission_required('stronghold.can_view_stronghold')
@login_required(login_url="/login/")
def code_detail(request, code_id):
    c = Code.objects.get(pk=code_id)
    return render(request, 'stronghold/code_detail.html', {'code': c})

@permission_required('stronghold.can_view_stronghold')
@login_required(login_url="/login/")
def code_delete(request, code_id):
    code = Code.objects.get(pk=code_id)
    code.delete()
    return HttpResponseRedirect('/stronghold/')

stronghold/templates/stronghold/code_add.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add a new Code</h1>

    <section>
        <form method="post" action="{% url 'stronghold:code_add' %}">
            {% csrf_token %}
            <p>
                {{ form }}
            </p>
            <p>
                <small>Don't see the door you want? <a href="{% url 'stronghold:door_add' %}">+ Add a new door</a></small>
            </p>
            <p>
                <input type="submit" value="Add this Code">
            </p>
        </form>
    </section>
{% endblock %}

stronghold/templates/stronghold/code_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Code</h1>
    <section>
        <h3>Door Code</h3>
        <p>{{ code.door }}</p>
        <p>{{ code.number }}</p>
        <p>{{ code.permanent }}</p>
        <p>{{ code.belongs_to }}</p>
        
    </section>
    <section>
        <a class="delete" href="{% url 'stronghold:code_delete' code.id %}">x delete this door</a>
    </section>
{% endblock %}

stronghold/templates/stronghold/door_add.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add a new Door</h1>

    <section>
        <form method="post" action="{% url 'stronghold:door_add' %}">
            {% csrf_token %}
            <p>
                {{ form }}
            </p>
            <p>
                <input type="submit" value="Add this Door">
            </p>
        </form>
    </section>
{% endblock %}

stronghold/templates/stronghold/overview.html
{% extends 'base.html' %}

{% block content %}
<h1>Stronghold</h1>
<section>
    <h3>Permanent Codes</h3>
    <p>
        <a class="action-button" href="{% url 'stronghold:code_add' %}">+ Add a new code</a>
    </p>
    {% if perm_codes %}
        <ul>
        {% for code in perm_codes %}
            <li><a href="{% url 'stronghold:code_detail' code.id %}">{{ code.number }}{% if door.location %}, located at {{ code.door.location }}{% endif %} {{ code.belongs_to }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no codes yet.</p>
    {% endif %}
</section>
<section>
    <h3>Temporary Codes</h3>
    {% if tmp_codes %}
        <ul>
        {% for code in tmp_codes %}
            <li><a href="{% url 'stronghold:code_detail' code.id %}">{{ code.number }}{% if door.location %}, located at {{ code.door.location }}{% endif %} {{ code.belongs_to }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no codes yet.</p>
    {% endif %}
</section>
{% endblock %}