astelle/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.shortcuts import render

urlpatterns = [
    url(r'^kronos/', include('kronos.urls', namespace="kronos")),
    url(r'^hq/', include('hq.urls', namespace="hq")),
    url(r'^admin/', include(admin.site.urls)),
]

hq/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.overview, name="overview"),
    path('project/add/', views.project_add, name="project_add"),
    path('project/<int:project_id>/', include([
        path('', views.project_detail, name="project_detail"),
        path('archive/', views.project_archive, name="project_archive"),
        path('delete/', views.project_delete, name="project_delete"),
        ])),
    path('address/add/', views.address_add, name="address_add"),
    path('address/<int:address_id>', include([
        path('', views.address_detail, name="address_detail"),
        path('delete/', views.address_delete, name="address_delete"),
        ])),
]

timekeeper/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
]

workroom/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('kronos/', include(('kronos.urls', 'kronos'), namespace='kronos')),
    path('atom/', include(('atom.urls', 'atom'), namespace='atom')),
    path('hq/', include(('hq.urls', 'hq'), namespace='hq')),
    path('stronghold/', include(('stronghold.urls', 'stronghold'), namespace='stronghold')),
    path('admin/', admin.site.urls),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ page_title }}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="description" content="">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {% block stylesheets %}
    {% endblock %}
</head>
<body>
    <header>
        <!-- <a class="username" href="">{{ user.first_name }} {{ user.last_name }}</a> -->
        <h1>
            <a class="logo" href="{% url 'kronos:overview' %}">WORKROOM</a>
        </h1>
        {% if user.is_authenticated %}
            <nav>
                <p>
                    <a class="logout" href="{% url 'logout' %}">Logout</a>
                    <a href="{% url 'kronos:overview' %}">Timecards</a>
                    <a href="{% url 'hq:overview' %}">Projects</a>
                    <a href="{% url 'atom:overview' %}">Labor Classes</a>
                    <!-- <a href="{% url 'stronghold:overview' %}">stronghold</a> -->
                </p>
            </nav>
        {% else %}
            <nav>
                <p>
                    <a class="login" href="{% url 'login' %}">Login</a>
                    <a href="">Home</a>
                    <a href="">About</a>
                </p>
            </nav>
        {% endif %}
    </header>

    <article>
        {% block content %}
        {% endblock %}
    </article>

    <footer>
    </footer>
    <script src="{% static 'js/index.js' %}"></script>
    {% block javascripts %}
    {% endblock %}
</body>
</html>

templates/overview.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ user.first_name, user.last_name }}</h1>
{% endblock %}